# Generated by Django 5.0.14 on 2026-09-20 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_label', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_label', models.CharField(max_length=255)),
                ('requested_time', models.DateTimeField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('seats_needed', models.PositiveIntegerField()),
                ('booking_type', models.CharField(choices=[('NOW', 'Now'), ('SCHEDULED', 'Scheduled')], default='NOW', max_length=20)),
                ('ride_access_type', models.CharField(choices=[('SHARED', 'Shared'), ('PRIVATE', 'Private'), ('WHOLE_VEHICLE', 'Whole Vehicle')], default='SHARED', max_length=20)),
                ('transport_mode', models.CharField(blank=True, choices=[('BODA', 'Boda Boda'), ('BAJAI', 'Bajaji'), ('CAR', 'Car'), ('VAN', 'Van'), ('BUS', 'Bus')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SCHEDULED', 'Scheduled'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation'), ('CONFIRMED', 'Confirmed'), ('MATCHING', 'Matching'), ('MATCHED', 'Matched'), ('BOOKED', 'Booked'), ('FULFILLED', 'Fulfilled'), ('NO_MATCH_FOUND', 'No Match Found'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='SUBMITTED', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_requests', to='accounts.passengerprofile')),
            ],
            options={
                'db_table': 'rider_requests_riderrequest',
                'indexes': [models.Index(fields=['status'], name='rider_reque_status_110211_idx'), models.Index(fields=['booking_type', 'scheduled_for'], name='rider_reque_booking_4ecd3e_idx')],
            },
        ),
    ]
