# Generated by Django 5.0.14 on 2026-09-20 19:15

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journey_type', models.CharField(choices=[('PROFESSIONAL', 'Professional Service'), ('COMMUNITY_JOURNEY', 'Community Journey')], default='PROFESSIONAL', max_length=30)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_label', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_label', models.CharField(max_length=255)),
                ('planned_route', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_departure_time', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FULL', 'Full'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_plans', to='accounts.providerprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_plans', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'journey_plans_journeyplan',
                'indexes': [models.Index(fields=['status', 'scheduled_departure_time'], name='journey_pla_status_721e9d_idx'), models.Index(fields=['journey_type'], name='journey_pla_journey_c23f6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='JourneyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_label', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_label', models.CharField(max_length=255)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('departure_time', models.TimeField()),
                ('total_seats', models.IntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_templates', to='accounts.providerprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_templates', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'journey_plans_template',
                'indexes': [models.Index(fields=['is_active'], name='journey_pla_is_acti_1a859a_idx')],
            },
        ),
    ]
