# Generated by Django 5.0.14 on 2026-09-20 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journey_plans', '0001_initial'),
        ('rider_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('proposed_fare_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_pickup_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PROPOSED', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_proposals', to='journey_plans.journeyplan')),
                ('rider_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_proposals', to='rider_requests.riderrequest')),
            ],
            options={
                'db_table': 'matching_matchproposal',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='matching_ma_status_6ea68a_idx')],
            },
        ),
    ]
