# Generated by Django 5.0.14 on 2026-09-20 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('BODA_BODA', 'Boda Boda'), ('BAJAI', 'Bajaji'), ('CAR', 'Car'), ('BUS', 'Bus')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.providerprofile')),
            ],
            options={
                'db_table': 'vehicles_vehicle',
            },
        ),
    ]
