# Generated by Django 5.0.14 on 2026-09-20 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPESA', 'M-PESA'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('gateway_response', models.JSONField(default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shared_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.sharedcost')),
            ],
            options={
                'db_table': 'payments_payment',
            },
        ),
    ]
