# Generated by Django 5.0.14 on 2026-09-20 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('journey_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_approved', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.providerprofile')),
            ],
            options={
                'db_table': 'payouts_provider_payout',
            },
        ),
        migrations.CreateModel(
            name='ProviderEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available for payout'), ('PAID_OUT', 'Paid out'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_earning', to='bookings.booking')),
                ('journey_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_earnings', to='journey_plans.journeyplan')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='accounts.providerprofile')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='payouts.providerpayout')),
            ],
            options={
                'db_table': 'payouts_provider_earning',
            },
        ),
        migrations.AddIndex(
            model_name='providerpayout',
            index=models.Index(fields=['provider', 'status'], name='payouts_pro_provide_658477_idx'),
        ),
        migrations.AddIndex(
            model_name='providerpayout',
            index=models.Index(fields=['status'], name='payouts_pro_status_c22b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerearning',
            index=models.Index(fields=['provider', 'status'], name='payouts_pro_provide_c0d460_idx'),
        ),
        migrations.AddIndex(
            model_name='providerearning',
            index=models.Index(fields=['status'], name='payouts_pro_status_72a776_idx'),
        ),
    ]
